sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t himanshi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true himanshi/docker-react npm run test


  
